#include "stm32f10x.h"
#include <stdlib.h> 

//max amount of rounds.
int gameRounds = 5;
int numLeds = 4;

/*
	LED1 through LED4 turn on specific LEDs by setting bits in the ODR.
*/
void LED1On();
void LED2On(); 
void LED3On(); 
void LED4On(); 

/*
	LED1 through LED4 turn off specific LEDs by clearing bits in the ODR.
*/
void LED1Off(); 
void LED2Off(); 
void LED3Off(); 
void LED4Off(); 

/*
	sets up the GPIO pins by enabling the GPIOA, GPIOB clocks. Configures pin modes throgh CRL and CRH
*/
void initilization();

/*
	delay used throughout the program, made via nested loops.
*/
void delay(int time);

/*
	functions that are in charge of turning off all the leds and turning on all leds.
*/
void all_leds_off();
void all_leds_on();

/*
	incharge of the knight rider sequence.
	waits for any button to be pushed to begin the rounds of the game.
*/
unsigned int waitStart();

/*
	function from the lab, generates random numbers ranging from 0-3 for led selection.
	uses the seed for randomizing,
*/
int randomNumberTo4(unsigned int seed);

/*
	shows the pattern thats generated by lighting up the leds in sequence.
	each led stays on for 1 second with 1 second gap in between patterns.
*/
void patternDisplay(int *pattern, int size);

/*
	waits for a button press.
	checks if the pressed buttons match the pattern that was outputted.
	has a 5 second timeout for each input.
	returns seed if value if input matches, 0 if wrong.
*/
unsigned int buttonCheck(int *pattern, int size);

/*
	these functions are in charge of displaying appropriate patterns for winning and losing.
*/
void gameOver();
void gameWon();

/*
	displays the final score using leds, via the binary format. The MSB is A0 and LSB is A3. 
*/
void binaryResult(int score);

/*
	checks if any button is currently pressed.
	returns 1 if pressed, 0 if not.
*/
int activeButtonCheck();
